"""simplify mortgage_payment to id, month, amount

Revision ID: 462cc5612ff4
Revises: 0583ecbea334
Create Date: 2026-08-26 18:32:28.506302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462cc5612ff4'
down_revision: Union[str, Sequence[str], None] = '0583ecbea334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortgage_payment', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('mortgage_payment', 'remaining_balance')
    op.drop_column('mortgage_payment', 'interest_amount')
    op.drop_column('mortgage_payment', 'total_payment')
    op.drop_column('mortgage_payment', 'principal_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortgage_payment', sa.Column('principal_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('mortgage_payment', sa.Column('total_payment', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('mortgage_payment', sa.Column('interest_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('mortgage_payment', sa.Column('remaining_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('mortgage_payment', 'amount')
    # ### end Alembic commands ###
