"""add current_value and current_value_updated_at to property

Revision ID: d1c79f6dd1c4
Revises: 462cc5612ff4
Create Date: 2026-08-28 14:32:01.109749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c79f6dd1c4'
down_revision: Union[str, Sequence[str], None] = '462cc5612ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('property', sa.Column('current_value_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'current_value_updated_at')
    op.drop_column('property', 'current_value')
    # ### end Alembic commands ###
