"""add content_hash to document

Revision ID: f1f0c6d4ba04
Revises: 4a4825d06ed1
Create Date: 2026-08-22 20:31:04.849087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f0c6d4ba04'
down_revision: Union[str, Sequence[str], None] = '4a4825d06ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_document_content_hash', 'document', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_content_hash', 'document', type_='unique')
    op.drop_column('document', 'content_hash')
    # ### end Alembic commands ###
